PROJECT_DIR	= .
USER_LIB_PATH	:=  $(PROJECT_DIR)/lib
USER_LIB_PATH	:= /home/sjoer/sketchbook/libraries/
BOARD_TAG	= mega2560
CPPFLAGS	= -pedantic -Wall -Wextra
CURRENT_DIR	= $(shell basename $(CURDIR))
OBJDIR		= $(PROJECT_DIR)/bin/$(BOARD_TAG)/$(CURRENT_DIR)
ARDMK_DIR	= /usr/share/arduino
include $(ARDMK_DIR)/Arduino.mk

